name: qlcv
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  cupertino_icons: ^1.0.6
  collection: ^1.17.2
  equatable: ^2.0.5
  flow_builder: ^0.0.9
  flutter_bloc: ^8.1.3
  flutter_app_badger: ^1.5.0
  flutter_downloader: ^1.11.3
  flutter_local_notifications: ^16.1.0
  flutter_inappwebview: ^5.8.0
  firebase_messaging: ^14.6.9
  firebase_core: ^2.17.0
  get_it: ^7.6.4
  http: ^1.1.0
  object_mapper: ^1.2.1
  permission_handler: ^8.3.0

  path_provider: ^2.1.1
  stream_transform: ^2.1.0
  shared_preferences: ^2.2.1
  uuid: ^4.1.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:

  uses-material-design: true

  assets:
      - assets/logo.png
      - assets/user.png
      - assets/menu4.jpg
      - assets/image-icon.png
      - assets/trenet.png